theme: jekyll-theme-cayman
title: Veterans Information Resource
description: Veterans Information Resource

plugins:
  - jekyll-feed
  - jekyll-default-layout
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-mentions
  - jekyll-include-cache
  - jekyll-titles-from-headings
  - jemoji

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: true
  footnote_nr: 1
  entity_output: as_char
  smart_quotes: ["lsquo", "rsquo", "ldquo", "rdquo"]
  math_engine: mathjax
