# .github/workflows/lint-and-links.yml
name: Lint and Link Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  markdown-lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v14
        with:
          globs: '**/*.md'

  link-checker:
    name: Link Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Lychee Link Checker
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          # Check all markdown files
          args: "**/*.md"
          # Optional: increase timeout for slow sites
          # timeout: 90
